# Generated by Django 5.0.6 on 2024-08-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_rubric_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
