# Generated by Django 5.0.6 on 2024-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_img_bb_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d', verbose_name='Файлы')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображение'},
        ),
    ]
